version: '3'

services:
  grpc-svc:
    image: benjaminslabbert/grpc-linkerd-k8s-example-grpc-server:1.0.4-1563388274
    ports:
      - "50051"
    environment:
      - GRPC_PORT=50051

  grpc-client:
    image: benjaminslabbert/grpc-linkerd-k8s-example-grpc-client:1.0.4-1563388274
    ports:
      - "50051"
    environment:
      - GRPC_HOST=grpc-svc:50051
    depends_on:
      - grpc-svc
