apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grpc-client
  template:
    metadata:
      labels:
        component: grpc-client
    spec:
      containers:
        - name: grpc-client
          image: benjaminslabbert/grpc-linkerd-k8s-example-grpc-client:1.0.4
          ports:
            - containerPort: 50051
