apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grpc-svc
  template:
    metadata:
      labels:
        component: grpc-svc
    spec:
      containers:
        - name: grpc-svc
          image: benjaminslabbert/grpc-linkerd-k8s-example-grpc-server:1.0.4-1563388274
          ports:
            - containerPort: 50051
              name: grpc
          env:
            - name: "GRPC_PORT"
              value: "50051"
