apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: grpc-backend
  template:
    metadata:
      labels:
        component: grpc-backend
    spec:
      containers:
        - name: grpc-backend
          image: benjaminslabbert/grpc-linkerd-k8s-example-grpc-server:1.0.4
          ports:
            - containerPort: 50051
