apiVersion: v1
kind: Service
metadata:
  name: grpc-backend
spec:
  type: ClusterIP
  selector:
    component: grpc-backend
  ports:
    - port: 50051 # port used by other pods to connect to this service
      targetPort: 50051 # port of the container inside this service
