apiVersion: v1
kind: Service
metadata:
  name: grpc-client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: grpc-client
  ports:
    - port: 50051 # port used by other pods to connect to this service
      targetPort: 50051 # port of the container inside this service
